### ISSUE TITLE
Sonoff server error since 31 build

### ISSUE THREAD

**Issue by mcinnes01** [gerswin/ihomeaddons#1]
Hi,

I am getting the following error since the last update to version 31.

`0|sonoff.server  | TypeError: Cannot read property 'IP' of undefined
0|sonoff.server  |     at /usr/bin/sonoff/sonoff.server.module.js:178:37
0|sonoff.server  |     at Layer.handle [as handle_request] (/usr/bin/sonoff/node_modules/express/lib/router/layer.js:95:5)
0|sonoff.server  |     at next (/usr/bin/sonoff/node_modules/express/lib/router/route.js:137:13)
0|sonoff.server  |     at Route.dispatch (/usr/bin/sonoff/node_modules/express/lib/router/route.js:112:3)
0|sonoff.server  |     at Layer.handle [as handle_request] (/usr/bin/sonoff/node_modules/express/lib/router/layer.js:95:5)
0|sonoff.server  |     at /usr/bin/sonoff/node_modules/express/lib/router/index.js:281:22
0|sonoff.server  |     at Function.process_params (/usr/bin/sonoff/node_modules/express/lib/router/index.js:335:12)
0|sonoff.server  |     at next (/usr/bin/sonoff/node_modules/express/lib/router/index.js:275:10)
0|sonoff.server  |     at urlencodedParser (/usr/bin/sonoff/node_modules/body-parser/lib/types/urlencoded.js:82:7)
0|sonoff.server  |     at Layer.handle [as handle_request] (/usr/bin/sonoff/node_modules/express/lib/router/layer.js:95:5)`

Many thanks

Andy

**Comment by gerswin** [comment]
is now fixed
