### ISSUE TITLE
Sonoff server doesn't seem to run since 33

### ISSUE THREAD

**Issue by mcinnes01** [gerswin/ihomeaddons#2]
Hi

Since 33 the sonoff server no longer seems to run. There are no logs coming out at all where normally at info level I would get a fair bit of detail.

Tried restarting the add-on, hassio and hassos, then stating the sonoff server to no avail.

Many thanks 

Andy

**Comment by gerswin** [comment]
let me check, thanks

**Comment by gerswin** [comment]
hello, i'm using version 33 of sonoff server without any problem, you can't start your server?

**Comment by mcinnes01** [comment]
It's randomly started now and seems to be working fine with logs coming out. It was started but there were no logs. I restarted all my sonoffs manually then they reconnected and I started getting logs again.

**Comment by gerswin** [comment]
when sonoff lost connection with your server for longs periods you must restart your sonoff device :(

**Comment by mcinnes01** [comment]
That is probably it, I guess in my electric cabinets I could power the sonoffs with some other smart device to allow me to remotely reset them if necessary. Thanks
